### ISSUE TITLE
Keeping the releases in the repository is not sustainable

### ISSUE THREAD

**Issue by clhodapp** [d40cht/sbt-cpp#28]
Hey.

I just wanted to point out that keeping your releases in the same repository as your source is not sustainable. Due to the nature of git, every single "git clone" for the rest of your project's lifetime will cause complete copies of those releases to be downloaded (although some gain will be made to due git's excellent compression). Worse, to some degree, the damage is already done; When I make a checkout of your repository, I download 8.2 MiB of data. This creates a working directory with a size of ~17MiB. Of that 17, 15MiB is taken up by releases. However, things could be far worse: if this keeps up, you'll end up with a hundreds-of-MiB repository that is a complete pain for everyone to deal with. Therefore, I urge you to 1) Move your releases to a separate repository in the future or (even better) 2) Look at having them included in either Maven Central or the sbt Ivy repository.

**Comment by d40cht** [comment]
Very good point. I've been hosting them locally just because I haven't yet
felt that the project has enough traction to justify pushing up somewhere
more 'official'. As a relative newcomer to the java ecosystem, and up until
now only a consumer of maven/ivy artifacts, I'm not really sure what's
involved in getting things up to Maven Central or the sbt Ivy repo. How
does one go about submitting?

**Comment by jsuereth** [comment]
http://www.scala-sbt.org/release/docs/Community/Community-Plugins.html

Please feel free to use our repo!

**Comment by d40cht** [comment]
Thanks Josh. I will do from now on...

Alex
